apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: repoea
  description: Sin descripción
  annotations:
    github.com/project-slug: crlsquilumba/repoea
    github.com/branch-count: "1"
    github.com/has-gitflow: "false"
    github.com/default-branch: "master"
  links:
    - url: https://github.com/crlsquilumba/repoea/tree/master
      title: "✅ master — producción"
      icon: github
spec:
  type: library
  lifecycle: experimental
  owner: user:default/guest
